// <auto-generated />
namespace OITChauffer_WindowsForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addeddestinationaddresstoRideRequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddestinationaddresstoRideRequest));
        
        string IMigrationMetadata.Id
        {
            get { return "201812022329133_added destination address to RideRequest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
