// <auto-generated />
namespace OITChauffer_WindowsForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedpaymentsbyremovedcollectionsfromridersandchauffers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedpaymentsbyremovedcollectionsfromridersandchauffers));
        
        string IMigrationMetadata.Id
        {
            get { return "201812042241297_updated payments by removed collections from riders, and chauffers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
